### ISSUE TITLE
Link

### ISSUE THREAD

**Issue by NiackZ** [ElSwanko/nnm-club-anime#8]
Пытаюсь вставить ссылку на https://anidb.net/anime/14758 и пишет "Укажите ссылку на WA"

Если вставляю ссылку на WA то от него нет ответа, т.к. запрос с https(nnm) на http(wa)

**Comment by ElSwanko** [comment]
Да, с AniDB скрипт работать не будет, парсинг работает только по WA.

Насчёт проблемы в курсе, прорабатываю вариант с внешней апишкой для загрузки страниц, чтобы грузилось по https обычным xhr-запросом.

**Comment by ElSwanko** [comment]
Вроде пофиксили.
Знакомый поднял проксю для запросов на ВА, перевёл вызовы на работу с проксёй.
Теперь скрипт работает по https. В консоли будет много ругани, но что получилось, то получилось.
